stages:
  # ====================================================================
  # 0. СТАДИЯ ЗАГРУЗКИ ДАННЫХ
  # ====================================================================
  pull_data:
    cmd: python commands.py pull
    deps:
      - commands.py

  # ====================================================================
  # 1. СТАДИЯ ПОДГОТОВКИ ДАННЫХ
  # ====================================================================
  prepare:
    cmd: python defects_in_welds/data/data_module.py prepare
    # Зависит от скрипта и исходных данных, которые были загружены
    deps:
      - defects_in_welds/data/data_module.py
      - data/train
      - data/valid
      - data/test
    outs:
      - data_prepared.txt
    # Выходные параметры (метрики или артефакты)
    params:
      - prepare.img_size
      - prepare.augmentations

  # ====================================================================
  # 2. СТАДИЯ ОБУЧЕНИЯ МОДЕЛИ
  # ====================================================================
  train:
    cmd: python defects_in_welds/training/run_training.py
    # Зависит от кода и артефакта предыдущей стадии
    deps:
      - defects_in_welds/training/run_training.py
      - defects_in_welds/data/data_module.py
      - defects_in_welds/model/model.py
      - defects_in_welds/training/lit_module.py
      - configs/params.yaml
      - data_prepared.txt # Явная зависимость от выхода 'prepare'
    # Зависит от:
    outs:
      - checkpoints/best_model.ckpt
    # Метрики и логирование (MLflow)
    metrics:
      - metrics/history.json:
          cache: false
    params:
      - training.max_epochs
      - training.batch_size
      - training.learning_rate
      - model.architecture

  # ====================================================================
  # 3. СТАДИЯ ОЦЕНКИ
  # ====================================================================
  evaluate:
    cmd: python defects_in_welds/training/run_evaluation.py
    # Зависит от лучшей модели и тестового набора
    deps:
      - defects_in_welds/training/run_evaluation.py
      - checkpoints/best_model.ckpt
      - defects_in_welds/data/data_module.py # Для загрузки тестовых данных
    # Метрики для финальной оценки
    metrics:
      - metrics/final_metrics.json:
          cache: false
